import assert from 'node:assert/strict';
import { mkdtemp, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { createServer } from 'node:http';
import { DatabaseSync } from 'node:sqlite';
import { launch, importFile } from './native-app.mjs';

const root = await mkdtemp(join(tmpdir(), 'held-ledger-tauri-synthetic-'));
const profileA = join(root, 'a'), profileB = join(root, 'b');
let app;
const comparable = assets => assets.map(a => { const v = structuredClone(a); if (v.photoSource === 'generated_placeholder') delete v.photoSource; return v; });
const requests = [];
let fail = false;
const server = createServer((req, res) => {
  let raw = '';
  req.on('data', chunk => { raw += chunk; });
  req.on('end', () => {
    requests.push({ path: req.url, auth: req.headers.authorization, body: JSON.parse(raw) });
    res.writeHead(fail ? 503 : 200, { 'content-type': 'application/json' });
    res.end(JSON.stringify(fail ? { error: 'synthetic unavailable' } : { choices: [{ message: { content: JSON.stringify({ name: 'Mock 相机', category: '数码', price: 1234, est_value: 1100, bought_date: '2026-06-30', note: '合成测试' }) } }] }));
  });
});
await new Promise(r => server.listen(0, '127.0.0.1', r));
try {
  app = await launch(profileA);
  let page = app.page;
  assert.equal((await page.evaluate(() => dbGetAll())).length, 5);
  assert.match(await page.locator('#app').innerText(), /10,320/);
  await page.evaluate(() => route('todos'));
  assert.match(await page.locator('#app').innerText(), /演示礼品卡/);
  await page.evaluate(() => { S.cat = '数码'; route('assets'); });
  assert.equal(await page.locator('[data-act="asset"]').count(), 2);
  await page.evaluate(() => { S.cat = '全部'; route('action'); });
  await page.locator('#nlInput').fill('昨天 299 元买了一个背包');
  await page.locator('[data-act="nl-go"]').click();
  await page.locator('[data-act="nl-confirm"]').first().waitFor();
  await page.locator('#nlName').fill('合成背包');
  await page.locator('[data-act="nl-confirm"]').first().click();
  // Close immediately after mutation, without waiting for the former 500ms debounce.
  await app.close();
  app = await launch(profileA); page = app.page;
  let assets = await page.evaluate(() => dbGetAll());
  assert.equal(assets.length, 6);
  const first = assets.find(a => a.name === '合成背包');
  assert.ok(first);
  await page.evaluate(id => { S.currentAsset = id; route('asset-detail'); }, first.id);
  await page.locator('[data-act="edit"][data-arg="value"]').click();
  await page.locator('#editInput').fill('288.50');
  await page.locator('#editInput').press('Enter');
  await page.waitForFunction(() => ASSETS.find(a => a.name === '合成背包').value === 288.5);
  page.once('dialog', d => d.accept());
  await page.locator('[data-act="delete-asset"]').click();
  await page.locator('.undo-toast button').click();
  const png = Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAusB9Wl2nWQAAAAASUVORK5CYII=', 'base64');
  await page.evaluate(id => { S.currentAsset = id; route('asset-detail'); }, first.id);
  const imageInput = page.locator('input[type="file"][accept*="image"]').first();
  await imageInput.setInputFiles({ name: 'synthetic.png', mimeType: 'image/png', buffer: png });
  await page.waitForFunction(id => ASSETS.find(a => a.id === id).photoSource === 'user_upload', first.id);
  assert.notEqual(await page.locator('.dhero-photo').evaluate(el => getComputedStyle(el).backgroundImage), 'none', 'Uploaded image must actually be painted by native WebView2');
  const snapshot = await page.evaluate(() => exportableAssets());
  await app.close();
  app = await launch(profileA); page = app.page;
  assert.deepEqual(await page.evaluate(() => exportableAssets()), snapshot);
  await page.evaluate(id => { S.currentAsset = id; route('asset-detail'); }, first.id);
  assert.ok(await page.evaluate(id => getComputedStyle(document.querySelector('.dhero-photo')).backgroundImage.includes(ASSETS.find(a => a.id === id).photo), first.id), 'Restarted image must be painted, not merely stored');
  await page.evaluate(base => saveByok({ provider: 'custom', base, key: 'synthetic-token', model: 'mock-model' }), `http://127.0.0.1:${server.address().port}/v1`);
  await page.evaluate(() => route('action'));
  await page.locator('#nlInput').fill('合成相机');
  await page.locator('[data-act="nl-go"]').click();
  await page.locator('[data-act="nl-confirm"]').first().waitFor();
  assert.equal(await page.locator('#nlName').inputValue(), 'Mock 相机');
  await page.locator('[data-act="nl-confirm"]').first().click();
  assert.equal(requests[0].path, '/v1/chat/completions');
  assert.equal(requests[0].auth, 'Bearer synthetic-token');
  assert.equal(requests[0].body.model, 'mock-model');
  assets = await page.evaluate(() => dbGetAll());
  assert.equal(assets.length, 7);
  assert.equal(new Set(assets.map(a => a.id)).size, 7);
  assert.deepEqual(assets.find(a => a.id === first.id), (await page.evaluate(() => ASSETS)).find(a => a.id === first.id));
  fail = true;
  await page.evaluate(() => route('action'));
  await page.locator('#nlInput').fill('300 元买了一个背包');
  await page.locator('[data-act="nl-go"]').click();
  await page.locator('[data-act="nl-confirm"]').first().waitFor();
  assert.match(await page.locator('#app').innerText(), /503|失败|本地/);
  fail = false;
  await page.evaluate(() => route('action'));
  await page.locator('#nlInput').fill('重试相机');
  await page.locator('[data-act="nl-go"]').click();
  await page.locator('[data-act="nl-confirm"]').first().waitFor();
  assert.equal(await page.locator('#nlName').inputValue(), 'Mock 相机');
  await page.evaluate(async()=>{
    const original=ASSETS;
    const canvas=document.createElement('canvas');canvas.width=8;canvas.height=8;
    canvas.getContext('2d').fillRect(0,0,8,8);
    const embedded=canvas.toDataURL('image/png');
    const blob=URL.createObjectURL(await new Promise(resolve=>canvas.toBlob(resolve)));
    try{
      ASSETS=[{id:'embedded',name:'Embedded',photo:embedded},{id:'blob',name:'Blob',photo:blob}];
      const backup=await prepareBackup();
      if(backup.assets[0].photo!==embedded||!backup.assets[1].photo.startsWith('data:image/jpeg;base64,'))throw Error('Images were not embedded');
      if(ASSETS[1].photo!==blob)throw Error('Export mutated live ledger');
      ASSETS=[{id:'missing',name:'Missing photo',photo:'thumbs/does-not-exist.jpg'}];
      let rejected=false;
      try{await prepareBackup();}catch(e){rejected=e.message.includes('Missing photo');}
      if(!rejected)throw Error('Missing photo silently exported');
    }finally{ASSETS=original;URL.revokeObjectURL(blob);}
  });
  const payload = await page.evaluate(() => prepareBackup());
  assert.ok(!JSON.stringify(payload).includes('synthetic-token'));
  const exportedPath = join(root, 'synthetic-export.json');
  await writeFile(exportedPath, JSON.stringify(payload));
  await app.close();
  app = await launch(profileB); page = app.page;
  await importFile(page, exportedPath, 7);
  assert.deepEqual(comparable(await page.evaluate(() => exportableAssets())), comparable(payload.assets));
  await app.close();
  app = await launch(profileB); page = app.page;
  assert.deepEqual(comparable(await page.evaluate(() => exportableAssets())), comparable(payload.assets));
  // Empty is a legitimate ledger and must survive a full process restart.
  await page.evaluate(() => { ASSETS = []; saveAssets(); });
  await app.close();
  app = await launch(profileB);
  assert.deepEqual(await app.page.evaluate(() => dbGetAll()), []);
  // A real SQLite failure must preserve disk data and prevent a native close.
  const database = new DatabaseSync(join(profileB, 'ledger.sqlite3'));
  database.exec("CREATE TRIGGER reject_write BEFORE UPDATE ON state BEGIN SELECT RAISE(FAIL, 'synthetic write failure'); END");
  await app.page.evaluate(async () => { ASSETS = cloneAssets(DEFAULT_ASSETS); try { await saveAssets(); } catch {} });
  const refusedClose = new Promise(resolve => app.page.once('dialog', async d => { const message = d.message(); await d.accept(); resolve(message); }));
  app.requestClose();
  assert.match(await refusedClose, /保存失败，窗口未关闭/);
  assert.equal(app.child.exitCode, null);
  assert.deepEqual(JSON.parse(database.prepare("SELECT value FROM state WHERE id='assets'").get().value), []);
  database.exec('DROP TRIGGER reject_write'); database.close();
  await app.close();
  app = await launch(profileB);
  assert.equal((await app.page.evaluate(() => dbGetAll())).length, 5);
  await app.close(); app = null;
  console.log(JSON.stringify({ ok: true, scenarios: ['native boot', 'filters and todos', 'smart add immediate close and full restart', 'edit delete undo', 'image upload and restart', 'BYOK mock success failure retry', 'unique ID after restart', 'JSON round trip', 'empty ledger restart', 'SQLite failure keeps native window and existing data; retry persists'], root }));
} finally {
  if (app) await app.close();
  await new Promise(r => server.close(r));
}
